### ISSUE TITLE
Normalising the results from the /aviser/stats/timeline-endpoint

### ISSUE THREAD

**Issue by maxodsbjerg** [kb-dk/kb-labs-api#15]
When working with the timeline-endpoint it would be helpful to have a normalised results as well as the counts

Eg: 

```
Q: krig
Granularity: month 
startTime: 1864 
endTime: 1864 
```
Results in: 
```
"timestamp","editions","articles","pages"
"1864",492,1035,828
"1864",507,1036,835
"1864",450,856,687
"1864",434,804,666
"1864",392,702,584
"1864",494,1028,805
"1864",467,963,753
"1864",467,945,751
"1864",361,614,523
"1864",359,610,526
"1864",349,588,497
"1864",354,560,501
"total",5126,9741,7956
```
 Ideally the csv-structured would look like this: 
 
 `"timestamp","editions","articles","pages", "editions_percentage", "articles_percentage","pages_percentage"`

**Comment by tokee** [comment]
As mentioned in #16, normalisation can be tricky. Maybe best solved by having an explicit `Normalising query` parameter with the possibilities

 * `*:* (Smurf compatible)`
 * `recordBase:doms_aviser (only articles)`

A better explanation of the possibilities is needed.
