### ISSUE TITLE
Response returned as big text blop.

### ISSUE THREAD

**Issue by maxodsbjerg** [kb-dk/kb-labs-api#23]
Many students use Voyant-tools for text mining at beginner level. This tool supports document uploads and urls. There fore it could be a nice feature if you could have the fulltext_org returned without any metadata to "pollute" the text mining in Voyant. 

In other word it could be nice if there was a format option: "Only text in big blob".

**Comment by VictorHarbo** [comment]
@maxodsbjerg This is a nice idea. Would it make sense to have the editionId included in the response in a way, Voyant could recognize as document delimiter?

If i remember correctly Voyant has the capability to import multiple documents?
