### ISSUE TITLE
/aviser/export/pages -JPEGS of entire pages

### ISSUE THREAD

**Issue by maxodsbjerg** [kb-dk/kb-labs-api#38]
It would be great for Transkribus projects to have an endpoint, which delivers a .zip file with images of entire pages of newspaper in the jpeg format. 

So similar to /aviser/export/images, but with entire pages instead.

**Comment by VictorHarbo** [comment]
@maxodsbjerg & @johanheinsen Just letting you know that the first version is available at labs now: http://labs.statsbiblioteket.dk/labsapi/api//api-docs?url=/labsapi/api/openapi.json#/labsapi/exportImages
