### ISSUE TITLE
Update documentation after raise of year limit

### ISSUE THREAD

**Issue by maxodsbjerg** [kb-dk/kb-labs-api#5]
The documentation on the Swagger-site still notes "100 years". <br> This should be changed to 140 years - based on this change: 
https://github.com/kb-dk/kb-labs-api/commit/2b17f7e485250d1fdafe18966b247b416ef9ac5f

**Comment by tokee** [comment]
Domb oversight. Fixed in f793c0863852fb9e3fe9757f65533dbd3b829575
