### ISSUE TITLE
aviser/export/images - fullPage only returning a single page when using familyId:-query

### ISSUE THREAD

**Issue by maxodsbjerg** [kb-dk/kb-labs-api#50]
When trying to extract all the pages from the newspaper [Corsaren](https://da.wikipedia.org/wiki/Corsaren)(1840 - 1853 - coverage in Mediestream) only a single page is returned (a front page - "No. 550 - Fredagen d. 4. April 1851). 

metadate response: 
`{
  "license" : "Creative Commons Public Domain Mark 1.0 License.",
  "query_end_year" : 1853,
  "query_start_year" : 1840,
  "query" : "familyId:corsaren1840",
  "title" : "Metadata for image extraction from the Danish Royal Librarys newspaper API.",
  "extraction_time" : "Wed Jun 07 16:35:50 CEST 2023"
}`

**Comment by VictorHarbo** [comment]
I've just looked at the logs and it seems like the service isn't dedublicating as it should. I will try to get it fixed today.
