### ISSUE TITLE
Make -1 value available in Swagger UI 

### ISSUE THREAD

**Issue by maxodsbjerg** [kb-dk/kb-labs-api#9]
Wish: -1 as max value wont freeze the Swagger UI. <br> 
This a didactic concern as it might be hard or even counterproductive to explain that the response-URL is constructed via the Swagger UI, but we still have to tamper with it to retrieve all responses. <br>
I don't know if it is feasible and you could explain you way out of it, but it would be nice no to.

**Comment by tokee** [comment]
I can see the problem. I don't know if it is possible to trick the UI that way, but I'll look into it.

**Comment by tokee** [comment]
Update: @blekinge flexed his hacker skills and discovered a workaround: https://github.com/swagger-api/swagger-ui/issues/3832#issuecomment-860730706

Fix being applied in 3... 2... 1...
